routes/loaisach_routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from model.loaisach_model import getloaisach, them_loai_sach, sua_loai_sach, xoa_loai_sach

# Định nghĩa Blueprint
loaisach_bp = Blueprint('loaisach', __name__, url_prefix='/loaisach')

@loaisach_bp.route('/')
def get_loaisach():
    loaisachs = getloaisach()
    return render_template('loaisach.html', loaisachs=loaisachs)

@loaisach_bp.route('/them', methods=['POST'])
def them_loaisach():
    maLoai = request.form.get('maLoai')
    loaiSach = request.form.get('loaiSach')
    ghiChu = request.form.get('ghiChu')

    if not maLoai:
        flash('Vui lòng nhập mã loại sách', 'danger')
        return redirect(url_for('loaisach.get_loaisach'))
    if not loaiSach:
        flash('Vui lòng nhập tên loại sách', 'danger')
        return redirect(url_for('loaisach.get_loaisach'))

    # Gọi hàm them_loai_sach
    message = them_loai_sach(maLoai, loaiSach, ghiChu)
    if message == "Mã loại sách đã tồn tại":
        flash(message, 'danger')
    elif message == "Thêm loại sách thành công!":
        flash(message, 'success')
    else:
        flash(message, 'danger')

    return redirect(url_for('loaisach.get_loaisach'))

@loaisach_bp.route('/sua', methods=['POST'])
def sua_loaisach():
    maLoai = request.form.get('maLoai')
    loaiSach = request.form.get('loaiSach')
    ghiChu = request.form.get('ghiChu')

    if not maLoai or not loaiSach:
        flash('Vui lòng nhập đầy đủ thông tin!', 'danger')
        return redirect(url_for('loaisach.get_loaisach'))

    sua_loai_sach(maLoai, loaiSach, ghiChu)
    flash('Cập nhật loại sách thành công!', 'success')
    return redirect(url_for('loaisach.get_loaisach'))

@loaisach_bp.route('/xoa/<maLoai>', methods=['POST'])
def xoa_loaisach(maLoai):
    message = xoa_loai_sach(maLoai)

    if message == "Xóa loại sách thành công!":
        flash(message, 'success')
    else:
        flash(message, 'danger')  # Hiển thị lỗi nếu không thể xóa

    return redirect(url_for('loaisach.get_loaisach'))

routes/quanlysach_routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from model.quanlysach_model import getquanlysach
from routes.sach_routes import sach_bp

# Định nghĩa Blueprint
quanlysach_bp = Blueprint('quanlysach', __name__, url_prefix='/quanlysach')




@quanlysach_bp.route('/')
def get_quanlysach():
    quanlysachs = getquanlysach()
    return render_template('quanlysach.html', quanlysachs=quanlysachs)

routes/quanlytacgia_routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from model.tacgia_model import gettacgia, them_tac_gia, sua_tac_gia, xoa_tac_gia

# Định nghĩa Blueprint
tacgia_bp = Blueprint('tacgia', __name__, url_prefix='/tacgia')


@tacgia_bp.route('/')
def get_tacgia():
    tacgias = gettacgia()
    return render_template('tacgia.html', tacgias=tacgias)

@tacgia_bp.route('/them', methods=['POST'])
def them_tacgia():
    maTacGia = request.form.get('maTacGia')
    tenTacGia = request.form.get('tenTacGia')
    ghiChu = request.form.get('ghiChu')

    if not maTacGia:
        flash('Vui lòng nhập mã tac gia', 'danger')
        return redirect(url_for('tacgia.get_tacgia'))
    if not tenTacGia:
        flash('Vui lòng nhập tên loại sách', 'danger')
        return redirect(url_for('tacgia.get_tacgia'))

    # Gọi hàm them_loai_sach
    message = them_tac_gia(maTacGia, tenTacGia, ghiChu)
    if message == "Mã tac gia đã tồn tại":
        flash(message, 'danger')
    elif message == "Thêm tac gia thành công!":
        flash(message, 'success')
    else:
        flash(message, 'danger')

    return redirect(url_for('tacgia.get_tacgia'))

@tacgia_bp.route('/sua', methods=['POST'])
def sua_tacgia():
    maTacGia = request.form.get('maTacGia')
    tenTacGia = request.form.get('tenTacGia')
    ghiChu = request.form.get('ghiChu')

    if not maTacGia or not tenTacGia:
        flash('Vui lòng nhập đầy đủ thông tin!', 'danger')
        return redirect(url_for('tacgia.get_tacgia'))

    sua_tac_gia(maTacGia, tenTacGia, ghiChu)
    flash('Cập nhật tac gia thành công!', 'success')
    return redirect(url_for('tacgia.get_tacgia'))

@tacgia_bp.route('/xoa/<maTacGia>', methods=['POST'])
def xoa_tacgia(maTacGia):
    message = xoa_tac_gia(maTacGia)

    if message == "Xóa loại sách thành công!":
        flash(message, 'success')
    else:
        flash(message, 'danger')  # Hiển thị lỗi nếu không thể xóa

    return redirect(url_for('tacgia.get_tacgia'))

routes/sach_routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash

from model.loaisach_model import getloaisach
from model.nhaxuatban_model import getnxb
from model.sach_model import getsach, them_sach_new, sua_sach_new, xoa_sach_new
from model.tacgia_model import gettacgia

sach_bp = Blueprint('sach', __name__, url_prefix='/sach')


@sach_bp.route('/')
def get_sach():
    sachs = getsach()
    tacgias=gettacgia()
    nhaxuatbans=getnxb()
    loaisachs=getloaisach()
    return render_template('sach.html',sachs=sachs, tacgias=tacgias, nhaxuatbans=nhaxuatbans, loaisachs=loaisachs)


@sach_bp.route('/them', methods=['POST'])
def them_sach():
    maSach = request.form.get('maSach')
    tenSach = request.form.get('tenSach')
    tacGia = request.form.get('tacGia')  # Lấy mã tác giả
    nhaXuatBan = request.form.get('nhaXuatBan')
    loaiSach = request.form.get('loaiSach')
    soTrang = request.form.get('soTrang')
    giaBan = request.form.get('giaBan')
    soLuong = request.form.get('soLuong')
    hinhAnh = request.form.get('hinhAnh')

    # Kiểm tra dữ liệu hợp lệ
    if not maSach:
        flash('Vui lòng nhập mã sach', 'danger')
        return redirect(url_for('sach.get_sach'))
    if not tenSach:
        flash('Vui lòng nhập tên sach', 'danger')
        return redirect(url_for('sach.get_sach'))

        # Gọi hàm them_loai_sach
    message = them_sach_new(maSach, tenSach, tacGia,nhaXuatBan,loaiSach,soTrang,giaBan,soLuong,hinhAnh)
    if message == "Mã Sach đã tồn tại":
        flash(message, 'danger')
    elif message == "Thêm sách thành công!":
        flash(message, 'success')
    else:
        flash(message, 'danger')

    return redirect(url_for('sach.get_sach'))

@sach_bp.route('/sua', methods=['POST'])
def sua_sach():
    maSach = request.form.get('maSach')
    tenSach = request.form.get('tenSach')
    tacGia = request.form.get('tacGia')  # Lấy mã tác giả
    nhaXuatBan = request.form.get('nhaXuatBan')
    loaiSach = request.form.get('loaiSach')
    soTrang = request.form.get('soTrang')
    giaBan = request.form.get('giaBan')
    soLuong = request.form.get('soLuong')
    hinhAnh = request.form.get('hinhAnh')

    if not maSach or not tenSach:
        flash('Vui lòng nhập đầy đủ thông tin!', 'danger')
        return redirect(url_for('sach.get_sach'))

    sua_sach_new(maSach, tenSach, tacGia,nhaXuatBan,loaiSach,soTrang,giaBan,soLuong,hinhAnh)
    flash("Cập nhật sách thành công!", 'success')
    return redirect(url_for('sach.get_sach'))

@sach_bp.route('/xoa/<maSach>', methods=['POST'])
def xoa_sach(maSach):
    message = xoa_sach_new(maSach)

    if message == "Xóa sach thành công!":
        flash(message, 'success')
    else:
        flash(message, 'danger')  # Hiển thị lỗi nếu không thể xóa

    return redirect(url_for('sach.get_sach'))

templates/baocaothongke.html
{% extends "base.html" %}

{% block title %}Quản Lý Sách - Hệ Thống Quản Lý Thư Viện{% endblock %}

{% block content %}
<div class="main-content">
    <!-- Header -->

    <div class="header-baocaothongke">Báo cáo Thống kê</div>


    <!-- Thống Kê Sách -->
    <div class="section-baocaothongke">
        <h3>Thống Kê Sách</h3>
        <div class="stat-group-baocaothongke">
            <div class="stat-box-baocaothongke purple">
                <i class="fas fa-book"></i>
                <p class="stat-number">{{ tongsachs }}</p>
                <p class="stat-label">Sách</p>
            </div>
            <div class="stat-box-baocaothongke pink">
                <i class="fas fa-book-open"></i>
                <p class="stat-number">{{ tongloaisachs }}</p>
                <p class="stat-label">Loại Sách</p>
            </div>
            <div class="stat-box-baocaothongke blue-light">
                <i class="fas fa-user"></i>
                <p class="stat-number">{{ tongnhanviens }}</p>
                <p class="stat-label">Tác Giả</p>
            </div>
            <div class="stat-box-baocaothongke green-dark">
                <i class="fas fa-building"></i>
                <p class="stat-number">{{ tongnhanviens }}</p>
                <p class="stat-label">Nhà Xuất Bản</p>
            </div>
        </div>
    </div>
    
    <!-- Thống kê Nhân viên - Độc giả - Số sách mượn -->
    <div class="section-baocaothongke">
        <h3>Thống kê Nhân viên - Độc giả - Số sách mượn</h3>
        <div class="stat-group-baocaothongke">
            <div class="stat-box-baocaothongke orange">
                <i class="fas fa-users"></i>
                <p class="stat-number">{{ tongsinhviens }}</p>
                <p class="stat-label">Sinh Viên</p>
            </div>
            <div class="stat-box-baocaothongke blue-dark">
                <i class="fas fa-book-reader"></i>
                <p class="stat-number">{{ tongsachmuons }}</p>
                <p class="stat-label">Sách Mượn</p>
            </div>
            <div class="stat-box-baocaothongke cyan">
                <i class="fas fa-user-tie"></i>
                <p class="stat-number">{{ tongnhanviens }}</p>
                <p class="stat-label">Nhân Viên</p>
            </div>
        </div>
    </div>
    

    <!-- Thống kê Sinh Viên Đang Mượn Sách và Quá Hạn -->
    <div class="section-baocaothongke">
        <h3>Thống kê Sinh Viên Đang Mượn Sách và Quá Hạn</h3>
        <div class="btn-group-baocaothongke">
            <a href="{{ url_for('danhsachdangmuon.get_danhsachdangmuon') }}" class="btn btn-danger">Danh Sách Đang Mượn</a>
            <a href="{{ url_for('danhsachquahan.get_danhsachquahan') }}" class="btn btn-danger">Danh Sách Quá Hạn</a>

        </div>

        {% block danhsach %}
            {% endblock %}
    </div>
</div>
{% endblock %}

templates/dangky.html
<!DOCTYPE html>
<html>
<head>
    <title>Forbidden</title>
</head>
<body>
    <h1>Truy cập bị từ chối</h1>
    <p>Bạn không có quyền truy cập vào trang này.</p>
    <a href="{{ url_for('home') }}">Quay về trang chủ</a>
</body>
</html>

templates/loaisach.html
{% extends "base.html" %}

{% block title %}Quản Lý Sách - Hệ Thống Quản Lý Thư Viện{% endblock %}

{% block content %}

<div class="main-content">
    <div class="header-loaisach">
        LOẠI SÁCH
    </div>

    <!-- Main Container -->
    <div class="container">
        <!-- Left Form Section -->
        <div class="left-section">
            <form method="POST">
              <div>
                <div class="form-group">
                    <label for="maLoai">Mã Loại</label>
                    <input type="text" id="maLoai" name="maLoai" >
                </div>
                <div class="form-group">
                    <label for="loaiSach">Loại Sách</label>
                    <input type="text" id="loaiSach" name="loaiSach" >
                </div>
                <div class="form-group">
                    <label for="ghiChu">Ghi Chú</label>
                    <input type="text" id="ghiChu" name="ghiChu">
                </div>
                <div>
                  {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        <div class="flash-messages">
                            {% for category, message in messages %}
                                <div class="alert alert-{{ category }}">{{ message }}</div>
                            {% endfor %}
                        </div>
                    {% endif %}
                {% endwith %}
                </div>
              </div>
              <div class="buttons-section">
                <button type="submit" formaction="{{ url_for('loaisach.them_loaisach') }}">Thêm</button>
                <button type="submit" formaction="{{ url_for('loaisach.sua_loaisach') }}">Sửa</button>
                <button type="reset">Làm mới</button>
            </div>

            </form>
        </div>

        <!-- Right Search and Table Section -->
        <div class="right-section">
            <div class="search-bar-loaisach">
                <input type="text" id="search-loaisach" onkeyup="searchFunction()" placeholder="Nhập mã hoặc tên loại sách để tìm kiếm...">
            </div>            
            <table>
                <thead>
                    <tr>
                        <th class="col-ma-loai">Mã loại sách</th>
                        <th class="col-ten-loai-sach">Tên loại</th>
                        <th class="col-ghi-chu">Ghi chú</th>
                        <th class="col-chuc-nang">Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                    {% for loaisach in loaisachs %}
                    <tr onclick="populateForm('{{ loaisach[0] }}', '{{ loaisach[1] }}', '{{ loaisach[2] }}')">
                        <td>{{ loaisach[0] }}</td>
                        <td>{{ loaisach[1] }}</td>
                        <td>{{ loaisach[2] }}</td>
                        <td class="col-chuc-nang-xoa-loaisach">
                            <form action="{{ url_for('loaisach.xoa_loaisach', maLoai=loaisach[0]) }}" method="POST" style="display:inline;">
                                <button type="submit" class="btn-delete-loaisach" onclick="return confirm('Bạn có chắc chắn muốn xóa loại sách này?');">
                                    <i class="fas fa-trash-alt"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    function populateForm(maLoai, loaiSach, ghiChu) {
        document.getElementById('maLoai').value = maLoai;
        document.getElementById('loaiSach').value = loaiSach;
        document.getElementById('ghiChu').value = ghiChu;
    }

</script>
<script>
    function searchFunction() {
        var input = document.getElementById("search-loaisach");
        var filter = input.value.toLowerCase();  // Chuyển thành chữ thường để tìm kiếm không phân biệt chữ hoa chữ thường
        var table = document.querySelector("table tbody");  // Lấy phần body của bảng
        var rows = table.getElementsByTagName("tr");  // Lấy tất cả các dòng trong bảng

        // Duyệt qua tất cả các dòng trong bảng
        for (var i = 0; i < rows.length; i++) {
            var cells = rows[i].getElementsByTagName("td");  // Lấy tất cả các ô trong dòng
            var match = false;  // Biến kiểm tra nếu dòng này có phù hợp với từ khóa tìm kiếm

            // Duyệt qua từng ô trong dòng
            for (var j = 0; j < cells.length; j++) {
                var cell = cells[j];
                if (cell) {
                    var text = cell.textContent || cell.innerText;  // Lấy nội dung của ô
                    if (text.toLowerCase().indexOf(filter) > -1) {
                        match = true;  // Nếu có ô nào trong dòng trùng khớp, đặt match = true
                        break;
                    }
                }
            }

            // Hiển thị dòng nếu có bất kỳ ô nào trùng khớp
            if (match) {
                rows[i].style.display = "";
            } else {
                rows[i].style.display = "none";  // Ẩn dòng nếu không có khớp
            }
        }
    }
</script>

{% endblock %}

templates/sach.html
{% extends "base.html" %}

{% block title %}Quản Lý Sách - Hệ Thống Quản Lý Thư Viện{% endblock %}

{% block content %}

<div class="main-content-sach">
    <div class="header-sach">
        SÁCH
    </div>
    <div class="container-sach">
        <input type="text" class="input-sach" id="tim-kiem" onkeyup="searchFunction()" placeholder="Tìm Kiếm">
        <div class="form-container-sach">
            <form method="POST">
                <div class="row-sach">
                    <div class="column-sach">
                        <label for="maSach">Mã Sách</label>
                        <input type="text" id="maSach" name="maSach">

                        <label for="tenSach">Tên Sách</label>
                        <input type="text" id="tenSach" name="tenSach">

                        <label for="tacGia">Tác Giả</label>
                        <select id="tacGia" name="tacGia" required>
                            {% for tacgia in tacgias %}
                            <option value="{{ tacgia[0] }}">{{ tacgia[1] }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="column-sach">
                        <label for="nhaXuatBan">Nhà Xuất Bản</label>
                        <select id="nhaXuatBan" name="nhaXuatBan" required>
                            {% for nhaxuatban in nhaxuatbans %}
                            <option value="{{ nhaxuatban[0] }}">{{ nhaxuatban[1] }}</option>
                            {% endfor %}
                        </select>

                        <label for="loaiSach">Loại Sách</label>
                        <select id="loaiSach" name="loaiSach" required>
                            {% for loaisach in loaisachs %}
                            <option value="{{ loaisach[0] }}">{{ loaisach[1] }}</option>
                            {% endfor %}
                        </select>

                        <label for="soTrang">Số trang</label>
                        <input type="text" id="soTrang" name="soTrang">
                    </div>

                    <div class="column-sach">
                        <label for="giaBan">Giá bán</label>
                        <input type="text" id="giaBan" name="giaBan">

                        <label for="soLuong">Số lượng</label>
                        <input type="text" id="soLuong" name="soLuong">

                        <label for="hinhAnh">Hình ảnh</label>
                        <input type="text" id="hinhAnh" name="hinhAnh">
                    </div>
                </div>
                <div>
                    {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                    <div class="flash-messages">
                        {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">{{ message }}</div>
                        {% endfor %}
                    </div>
                    {% endif %}
                    {% endwith %}
                </div>

                <div class="button-container-sach">
                    <button class="button-sach" formaction="{{ url_for('sach.them_sach') }}">Thêm</button>
                    <button class="button-sach" formaction="{{ url_for('sach.sua_sach') }}">Sửa</button>
                    <button class="button-sach" type="reset">Làm mới</button>
                </div>
            </form>
        </div>

        <div class="table-container-sach">
            <table class="table-sach">
                <thead>
                    <tr>
                        <th>Mã Sách</th>
                        <th>Tên Sách</th>
                        <th>Mã Tác Giả</th>
                        <th>Mã Nhà Xuất Bản</th>
                        <th>Mã Loại Sách</th>
                        <th>Số Trang</th>
                        <th>Giá Bán</th>
                        <th>Số Lượng</th>
                        <th>Hình Ảnh</th>
                        <th class="col-chuc-nang-tacgia">Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                    {% for sach in sachs %}
                    <tr
                        onclick="populateForm('{{ sach[0] }}', '{{ sach[1] }}', '{{ sach[2] }}', '{{ sach[3] }}', '{{ sach[4] }}', '{{ sach[5] }}', '{{ sach[6] }}', '{{ sach[7] }}', '{{ sach[8] }}')">
                        <td>{{ sach[0] }}</td>
                        <td>{{ sach[1] }}</td>
                        <td>{{ sach[2] }}</td>
                        <td>{{ sach[3] }}</td>
                        <td>{{ sach[4] }}</td>
                        <td>{{ sach[5] }}</td>
                        <td>{{ sach[6] }}</td>
                        <td>{{ sach[7] }}</td>
                        <td><img src="{{ url_for('duongdan_picture', filename=sach[8]) }}" alt="{{ sach[8] }}"
                                width="100" height="140"></td>
                        <td class="col-chuc-nang-xoa-sach">
                            <form action="{{ url_for('sach.xoa_sach', maSach=sach[0]) }}" method="POST"
                                style="display:inline;">
                                <button type="submit" class="btn-delete-sach"
                                    onclick="return confirm('Bạn có chắc chắn muốn loại sách này?');">
                                    <i class="fas fa-trash-alt"></i>
                                </button>
                            </form>
                        </td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    function populateForm(maSach, tenSach, tacGia, nhaXuatBan, loaiSach, soTrang, giaBan, soLuong, hinhAnh) {
        document.getElementById('maSach').value = maSach;
        document.getElementById('tenSach').value = tenSach;
        document.getElementById('tacGia').value = tacGia;
        document.getElementById('nhaXuatBan').value = nhaXuatBan;
        document.getElementById('loaiSach').value = loaiSach;
        document.getElementById('soTrang').value = soTrang;
        document.getElementById('giaBan').value = giaBan;
        document.getElementById('soLuong').value = soLuong;
        document.getElementById('hinhAnh').value = hinhAnh;
    }
</script>
<script>
    function searchFunction() {
        var input = document.getElementById("tim-kiem");  // Lấy giá trị từ ô tìm kiếm
        var filter = input.value.toLowerCase();  // Chuyển từ khóa tìm kiếm thành chữ thường
        var table = document.querySelector(".table-sach tbody");  // Lấy phần thân của bảng
        var rows = table.getElementsByTagName("tr");  // Lấy tất cả các dòng trong bảng

        // Duyệt qua tất cả các dòng trong bảng
        for (var i = 0; i < rows.length; i++) {
            var cells = rows[i].getElementsByTagName("td");  // Lấy tất cả các ô trong dòng
            var match = false;  // Biến kiểm tra nếu dòng này có phù hợp với từ khóa tìm kiếm

            // Duyệt qua từng ô trong dòng
            for (var j = 0; j < cells.length; j++) {
                var cell = cells[j];
                if (cell) {
                    var text = cell.textContent || cell.innerText;  // Lấy nội dung văn bản của ô
                    if (text.toLowerCase().indexOf(filter) > -1) {  // Nếu có ô nào khớp với từ khóa
                        match = true;
                        break;
                    }
                }
            }

            // Hiển thị dòng nếu có bất kỳ ô nào trùng khớp
            if (match) {
                rows[i].style.display = "";  // Hiển thị dòng
            } else {
                rows[i].style.display = "none";  // Ẩn dòng nếu không có khớp
            }
        }
    }
</script>

{% endblock %}

templates/tacgia.html
{% extends "base.html" %}

{% block title %}Quản Lý Sách - Hệ Thống Quản Lý Thư Viện{% endblock %}

{% block content %}
    <div class="header-tacgia">
        TÁC GIẢ
    </div>
    <div class="container-tacgia">
        <div class="form-section-tacgia">
            <form method="POST">
            <div class="form-group">
                <label for="maTacGia">Mã Tác Giả</label>
                <input type="text" id="maTacGia" name="maTacGia" >
            </div>
            <div class="form-group">
                <label for="tenTacGia">Tên Tác Giả</label>
                <input type="text" id="tenTacGia" name="tenTacGia" >
            </div>
            <div class="form-group">
                <label for="ghiChu">Ghi Chú</label>
                <input type="text" id="ghiChu" name="ghiChu">
            </div>
                <div>
                  {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        <div class="flash-messages">
                            {% for category, message in messages %}
                                <div class="alert alert-{{ category }}">{{ message }}</div>
                            {% endfor %}
                        </div>
                    {% endif %}
                {% endwith %}
                </div>
            <div class="button-section-tacgia">
                <button type="submit" formaction="{{ url_for('tacgia.them_tacgia') }}">Thêm</button>
                <button type="submit" formaction="{{ url_for('tacgia.sua_tacgia') }}">Sửa</button>
                <button type="reset">Làm mới</button>
            </div>
            </form>
        </div>
        <div class="table-section">
            <div class="search-group">
                <label for="search">Tìm Kiếm</label>
                <input type="text" id="search" onkeyup="searchFunction()" placeholder="Nhập mã hoặc tên tác giả...">
            </div>

            <table class="bangtacgia">
                <thead>
                    <tr>
                       <th class="col-ma-loai-tacgia">Mã Tác Giả</th>
                        <th class="col-ten-loai-sach-tacgia">Tên Tác Giả</th>
                        <th class="col-ghi-chu-tacgia">Ghi chú</th>
                        <th class="col-chuc-nang-tacgia">Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                    {% for tacgia in tacgias %}
                    <tr onclick="populateForm('{{ tacgia[0] }}', '{{ tacgia[1] }}', '{{ tacgia[2] }}')">
                        <td>{{ tacgia[0] }}</td>
                        <td>{{ tacgia[1] }}</td>
                        <td>{{ tacgia[2] }}</td>

                    <td class="col-chuc-nang-xoa-tacgia">
                        <form action="{{ url_for('tacgia.xoa_tacgia', maTacGia=tacgia[0]) }}" method="POST" style="display:inline;">
                            <button type="submit" class="btn-delete-tacgia" onclick="return confirm('Bạn có chắc chắn muốn xóa loại sách này?');">
                                <i class="fas fa-trash-alt"></i>
                            </button>
                        </form>
                </td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
</div>
<script>
function populateForm(maTacGia, tenTacGia, ghiChu) {
    document.getElementById('maTacGia').value = maTacGia;
    document.getElementById('tenTacGia').value = tenTacGia;
    document.getElementById('ghiChu').value = ghiChu;
 }

</script>
<script>
function searchFunction() {
    var input = document.getElementById("search");
    var filter = input.value.toLowerCase();  // Chuyển từ khóa tìm kiếm thành chữ thường
    var table = document.querySelector(".bangtacgia tbody");  // Chọn phần tbody của bảng
    var rows = table.getElementsByTagName("tr");  // Lấy tất cả các dòng trong bảng

    // Duyệt qua tất cả các dòng trong bảng
    for (var i = 0; i < rows.length; i++) {
        var cells = rows[i].getElementsByTagName("td");  // Lấy tất cả các ô trong dòng
        var match = false;  // Biến kiểm tra nếu dòng này có phù hợp với từ khóa tìm kiếm

        // Duyệt qua từng ô trong dòng
        for (var j = 0; j < cells.length; j++) {
            var cell = cells[j];
            if (cell) {
                var text = cell.textContent || cell.innerText;  // Lấy nội dung văn bản của ô
                if (text.toLowerCase().indexOf(filter) > -1) {  // Nếu có ô nào khớp với từ khóa
                    match = true;
                    break;
                }
            }
        }

        // Hiển thị dòng nếu có bất kỳ ô nào trùng khớp
        if (match) {
            rows[i].style.display = "";
        } else {
            rows[i].style.display = "none";  // Ẩn dòng nếu không có khớp
        }
    }
}
</script>

{% endblock %}